project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - "posts/**/translations-*.json"
  pre-render:
    - scripts/update_translations.py

website:
  title: "Lei's Note"
  site-url: "https://wulei.org"
  description: "Notes on research papers"
  navbar:
    logo: images/avatar.jpg
    left:
      - href: index.qmd
        text: Posts
      - href: about.qmd
        text: About
  page-footer:
    left: "© 2026 Wu Lei. All rights reserved."
    right: "Made by Human"

format:
  html:
    lang: en
    from: markdown-smart
    theme:
      light: simplex
      dark: darkly
    css: styles.css
    include-in-header: immersive-translate.html
    toc: true
    toc-title: "Contents"

execute:
  freeze: auto
